### PR TITLE
Misc fixes

### PR DESCRIPTION
**Pull request by ZVNexus**

### CODE REVIEW

**Comment by ZVNexus** [comment]
@TingPing @lionirdeadman 

I want NVIDIA users to test these, ideally RTX 4000 series users. Also a note, it seems like the GPU sandbox is a bad idea for all Electron apps. I haven't seen any Electron app not spew GPU errors without disabling the sandbox. Is this something we can do globally?

**Comment by lionirdeadman** [comment]
I don't think adding `org.freedesktop.secrets` is a good idea.

I don't think disabling the GPU sandbox is a good idea, it works just fine other than for a certain part of Nvidia users and disabling it breaks stuff for the another part of Nvidia users. If the issue is log spam as you say then I think that's fair to just leave it on. It exists for a good reason and it's how Discord ships it. This was only introduced as a workaround because it broke rendering on Nvidia with an older version of electron that Discord was shipping.

**Comment by ZVNexus** [comment]
Discord is asking for secrets, any reason we shouldn't grant it? We shouldn't be in the business of policing applications on what they can and can't do, and if it's not required upstream should remove it from the app.

**Comment by lionirdeadman** [comment]
AFAIK Discord is not asking for secrets, Electron is. It has not caused any harm to not grant it. The least amount of holes in the flatpak, the better.

**Comment by TingPing** [comment]
`libsecret` can work fine without the permission as there is a secrets portal. Just glancing at `components/os_crypt/libsecret_util_linux.cc` I'd expect it to work.

**Comment by ZVNexus** [comment]
@lionirdeadman Want to go ahead with this?

**Comment by lionirdeadman** [comment]
If TingPing is okay with this, no issue merging this personally.

It just seems like the logical choice for 'upstream-ability' of Discord. Speaking of, do we need to consult with Discord upstream on this front? I've not really been told much on this.. @TingPing @cassidyjames

**Pull request merged**
