### PR TITLE
Remove set-gtk-dark-theme.py and dependencies

### PR DESCRIPTION
**Pull request by lionirdeadman**
I want to remove this hack.

I think that this has created more maintenance headaches as its dependencies clog pull requests and break more than anything else in this repository.

I don't see how to update this script in a satisfying way to handle the new freedesktop settings in x11 and wayland.

Solutions like [Darkbar](https://flathub.org/apps/details/com.github.bluesabre.darkbar) exist now for those who still want their discord to have a dark bar.

### CODE REVIEW

**Comment by TingPing** [comment]
> I don't see how to update this script in a satisfying way to handle the new freedesktop settings in x11 and wayland.

Hmm? It is a trivial dbus call. I can add support for it later this week.

**Comment by TingPing** [comment]
> I think that this has created more maintenance headaches as its dependencies clog pull requests 

Lets just not get PRs for them then. You can configure it to only open PRs for app updates.

**Comment by TingPing** [comment]
I can rewrite it to *only* query the freedesktop dark mode. This will remove all dependencies and be more simple in general.

**Comment by TingPing** [comment]
It is very much a hack but I'm not worried about perfection.

I have no reason to believe Discord will ever spend time to change the behavior on Linux. *Maybe* upstream Electron will someday handle CSD properly on Linux and Discord gets fixed by chance.

**Review by hmenke — APPROVED** [review]

**Pull request closed without merging**
