### PR TITLE
Bump to v0.0.12

### LINKED ISSUE #107: New version 0.0.12 released
Hi,

today, Discord released a new version: 0.0.12
As usual, flatpak users are locked out once again.

### PR DESCRIPTION
**Pull request by gmes78**
Fixes #107

### CODE REVIEW

**Comment by gmes78** [comment]
(Unrelated: should flathubbot trigger a rebuild on a commit it already built?)

**Comment by barthalion** [comment]
You force pushed 2 times so 2 builds were triggered.

**Comment by gmes78** [comment]
I did, but the second was reverting to the original commit.

**Comment by gmes78** [comment]
Anyway, thanks for the quick merge.

**Comment by A6GibKm** [comment]
Must be your lucky day, there's a new update!

Thanks :confetti_ball:

**Pull request merged**
