### PR TITLE
Add `XDG_CURRENT_DESKTOP=KDE`

### PR DESCRIPTION
**Pull request by JakobDev**
Sometimes `XDG_CURRENT_SESSION` is not enough

### CODE REVIEW

**Comment by bbhtt** [comment]
The metadata needs to be converted to start with component node. Linter is not intelligent enough to catch it.

**Comment by TingPing** [comment]
> Sometimes XDG_CURRENT_SESSION is not enough

Could you find the actual source to this. Blindly guessing is not ideal.

**Comment by ProjectSynchro** [comment]
> > Sometimes XDG_CURRENT_SESSION is not enough
> 
> Could you find the actual source to this. Blindly guessing is not ideal.

Looking around this stackoverflow answer seems pretty helpful: https://superuser.com/a/1643180

Quoted:
> Old question, but still highly ranked on Google, so worth answering in 2021.

> You want to use only the official $XDG_CURRENT_DESKTOP. Be careful that it is a colon-separated list (like $PATH), so don't assume it only contains a single value (even if it is in most DEs). If you prefer to handle a single value, use $XDG_SESSION_DESKTOP.
>
>Official standards:
>
>   [XDG_CURRENT_DESKTOP](https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#recognized-keys), defined in the [Desktop Entry Specification](https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html) since its [version 1.2](https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#idm45632483466576)
>
>   [XDG_SESSION_DESKTOP](https://www.freedesktop.org/software/systemd/man/pam_systemd.html#desktop=), best described in [systemd's PAM](https://www.freedesktop.org/software/systemd/man/pam_systemd.html)
>
>    DESKTOP_SESSION is deprecated. Some DEs/WMs still set it for the sake of backward-compatibility, for new software it is not needed. It's 2021 after all.
>
>For more details, including a bash function to parse and test a desktop environment, see https://unix.stackexchange.com/a/645761/4919

Looking at the linked specifications, it seems like using $XDG_CURRENT_DESKTOP, is suggested, with $XDG_DESKTOP_SESSION being the deprecated option.

**Comment by pedrovanzella** [comment]
Shouldn't this be respecting the system's `XDG_CURRENT_DESKTOP` and `XDG_CURRENT_SESSION`?

FWIW, on my system `XDG_CURRENT_DESKTOP` is set to `KDE`, and `XDG_CURRENT_SESSION` is unset.

**Comment by guihkx** [comment]
>I had made a Electron PR to fix this which got merged, so then Problem will be gone with Electron 32. Until then we need this little workaround.

Discord 0.0.70 (released [yesterday](https://github.com/flathub/com.discordapp.Discord/pull/449)) now includes Electron 32.0.0.

Can you please check if this workaround is still necessary? Thank you.

**Comment by JakobDev** [comment]
> Can you please check if this workaround is still necessary? Thank you.

I can confirm that it works now and this PR is not needed anymore

**Pull request closed without merging**
