### PR TITLE
Use HW acceleration arguments for electron

### PR DESCRIPTION
**Pull request by lionirdeadman**
This doesn't disable the gpu blacklist so this won't actually change things for everyone.

I'm unsure why we need this when the Discord settings have an hw accel option but it appears to do nothing.

This however does seem to improve performance for people so we should do it.

I want people other than myself to test this.

### CODE REVIEW

**Comment by Vixtron** [comment]
I've been using this for a couple of months, greatly increased responsiveness, I suggested this change because people started complaining about laggy guild list.

**Comment by alvarlagerlof** [comment]
This brought a noticeable improvement for me. Before this:
- Hovering servers the sidebar to show the label or scrolling was regularly running like 15fps. Now it's a smooth 60.
- Scrolling also seems like it has improved overall.
- Typing now feels more instant (which I notice it wasn't before, I was just used to it being slow I guess.
- Gifs are no longer a problem.

**Comment by lionirdeadman** [comment]
Removed `--use-gl=desktop` as it appears to be unnecessary and will break in later chromium.

**Comment by nakobejo** [comment]
i try this build on Fedora 35 KDE Plasma X11 session with Nvidia GPU
so far feel smooth when scrolling sidebar

**Comment by TheEvilSkeleton** [comment]
Works like a charm for me.

**Comment by alvarlagerlof** [comment]
I get this when trying to launch on Wayland and Nvidia. The window does not show up. To be fair it wasn't exactly working before either (a black window). Might be related to something else though.

```
[alvar@rehoboam ~]$ flatpak run com.discordapp.Discord 
Disabling updates already done
[6 preload-host-spawn-strategy] Running: /app/bin/zypak-helper child - /app/discord/Discord --type=zygote
Traceback (most recent call last):
  File "/app/bin/set-gtk-dark-theme.py", line 17, in <module>
    disp = Xlib.display.Display()
  File "/app/lib/python3.9/site-packages/Xlib/display.py", line 89, in __init__
    self.display = _BaseDisplay(display)
  File "/app/lib/python3.9/site-packages/Xlib/display.py", line 71, in __init__
    protocol_display.Display.__init__(self, *args, **keys)
  File "/app/lib/python3.9/site-packages/Xlib/protocol/display.py", line 84, in __init__
    name, protocol, host, displayno, screenno = connect.get_display(display)
  File "/app/lib/python3.9/site-packages/Xlib/support/connect.py", line 73, in get_display
    return mod.get_display(display)
  File "/app/lib/python3.9/site-packages/Xlib/support/unix_connect.py", line 76, in get_display
    raise error.DisplayNameError(display)
Xlib.error.DisplayNameError: Bad display name ""
Discord 0.0.16
Failed to generate minidump./app/bin/discord: line 10:     6 Segmentation fault      (core dumped) env TMPDIR=$XDG_CACHE_HOME zypak-wrapper /app/discord/Discord --use-gl=desktop --enable-gpu-rasterization --enable-zero-copy "$@"
[alvar@rehoboam ~]$ 
```

**Comment by Lunarequest** [comment]
can confirm this works as intended

**Comment by alvarlagerlof** [comment]
Now that this is merged, will I get future updates automatically or do I need to reinstall from flathub?

**Comment by coderedart** [comment]
so, this fixed the sluggish server list on left until now. but it reverted back to being laggy again for me today :(

**Comment by coderedart** [comment]
> @coderedart You just updated your nvidia driver before flathub did. Wait a few minutes and `flatpak update`.

you are right. I updated drivers via pacman because flatpak has a weird bug that downloads the full driver package everytime https://github.com/flathub/org.freedesktop.Platform.GL.nvidia/issues/42 :(
Thanks for the solution, It was super irritating when it happened for weeks last time, so i didn't want to go through that again :D

**Pull request merged**
