### PR TITLE
Remove --disable-gpu for Nvidia on Wayland

### PR DESCRIPTION
**Pull request by lionirdeadman**
With newer Electron, I imagine the issues related to rendering on Nvidia hardware in a Wayland session should be fixed.

Needs testing

### CODE REVIEW

**Comment by retrixe** [comment]
Works fine for me (both through Xwayland and Wayland) on my laptop when running Discord with my NVIDIA GPU.

It's probably worth testing on a desktop or muxed laptop just in case though (where the display is directly linked to NVIDIA GPU), in case the bug occurs there.

**Review by TingPing — APPROVED** [review]
Lets give it a shot. Wayland is opt-in anyway and we have one KDE user reporting success.

**Comment by retrixe** [comment]
Afaik this bug affected Xwayland before?

**Comment by TingPing** [comment]
Oh you are totally right!

**Pull request closed without merging**
