### PR TITLE
Give home access with blacklisting of things it shouldn't access

### PR DESCRIPTION
**Pull request by lionirdeadman**
After discussion and a poll in #134, I have come to the conclusion that this will be the default level access for Discord.

I've probably forgotten/missed to remove access to certain things which is why I'm leaving this PR open for 2days. Feel free to open a PR if you miss this opportunity.

### CODE REVIEW

**Comment by ssokolow** [comment]
Here are the things I'm aware of which you're missing:

* `~/.bash_completion` (on Debian-family distros, this is sourced by `~/.bashrc`)
* `~/.bash_history` (My rcfiles are on GitHub. My command history is not. This isn't just because it changes frequently.)
* **`~/.cargo/credentials.toml` (Publishing credentials for Rust packages are stored here, which are a valuable target for attackers.Technically `$CARGO_HOME/credentials.toml`)**
* `~/.dbus` (I assume you only want it to be able to find the D-Bus security proxy)
* `~/.DCOPserver_*` (TDE applications never upgraded to D-Bus)
* `~/.gconf` (You'd be surprised how long it took for me to stop seeing GTK+ 1.2 applications in use well into the GTK+ 2.x era.)
* **`~/.gem/credentials` (According to the RubyGems docs, publishing credentials are stored here, which are a valuable target for attackers.)**
* `~/.gmrun_history` (My rcfiles are on GitHub. My command history is not. This isn't just because it changes frequently.)
* `~/.gnome2_private` (You'd be surprised how long it took for me to stop seeing GTK+ 1.2 applications in use well into the GTK+ 2.x era.)
* `~/.ICEauthority` (Again, TDE never upgraded off KDE 3.x's in-house IPC)
* `~/.jdownloader` (Could be used to steal your premium membership credentials for file lockers)
* `~/.macromedia` (Retiring Flash didn't delete its cookie store)
* **`~/.npmrc` (According to Azure docs, NPM publishing credentials are stored here, which are a valuable target for attackers)**
* **`~/.pypirc` (I can confirm that PyPI publishing credentials are stored here, which are a valuable target for attackers)**
* `~/.subversion` (I *believe* this is where it stores auth stuff)
* `~/.thunderbird` (All the same reasons you blacklist `.mozilla`)
* `~/.Trash-1000` (What if someone deletes a sensitive file?)
* `~/.wine` (Even if the user hasn't disabled desktop integration, plenty of Windows applications store sensitive information in the registry.)
* `~/.Xauthority`
* `~/.xsessionrc` (You missed an rcfile.)
* `~/.zhistory` (My rcfiles are on GitHub. My command history is not.)
* `~/Dropbox`

I have no clue if any of the non-Cargo credentials locations depend on environment variables, and I don't know enough about the Haskell, PHP, or C++ ecosystems to know where the credentials get stored for publishing Haskell packages to be downloaded by Cabal, PHP packages to be downloaded by Composer, C++ packages to be downloaded by Conan, vcget, etc. and so on.

**Comment by lionirdeadman** [comment]
`.DCOP_server_*` can't be done because wildcards don't work in this.
`.Trash-1000` isn't created in $HOME afaik, $HOME will use `.local/shared/Trash`.
`~/Dropbox` may want to have files shared, it has no credentials
`$CARGO_HOME` isn't recognized by flatpak-builder unfortunately.

**Comment by ssokolow** [comment]
> `.DCOP_server_*` can't be done because wildcards don't work in this.

That's a shame. There's a hostname in the `*` portion so there isn't even a "most likely name" that could be blacklisted.

> `.Trash-1000` isn't created in $HOME afaik, $HOME will use `.local/shared/Trash.`

Ahh, yeah. That's a holdover from 2012.

**Comment by TingPing** [comment]
I am very against this... It is completely unmaintainable. There is no such thing as a complete list of unsafe files, I could easily make a sandbox escape from what you came up with, and this package doesn't even have perfectly sandboxed permissions so it will always have escapes.

**Comment by lionirdeadman** [comment]
> I am very against this... It is completely unmaintainable. There is no such thing as a complete list of unsafe files, I could easily make a sandbox escape from what you came up with, and this package doesn't even have perfectly sandboxed permissions so it will always have escapes.

That is true and it is something I've acknowledged from the start. I can only limit it.

My other options if I want to make people happy are :
- Tell them to mess with the permissions which likely means just giving `$HOME` without any restrictions in which case they're in a worse position than this PR.
- Do this
- Try to make my own Electron build for Discord to implement file picking (no, I'm not doing that)

In any of those options, the X11 access and PA access are still potential ways to infect the machine anyways. There is no 100% secure option and this is the most maintainable option while still considering people's complaints.

I would've also really liked if you expressed that sentiment while I was polling people and requesting feedback because now it puts in a position where I've told people to vote for something and you're asking me to override their feedback.

**Comment by gmes78** [comment]
> * Try to make my own Electron build for Discord to implement file picking (no, I'm not doing that)

AFAIK, [this PR](https://github.com/electron/electron/pull/19159) would implement that.

**Comment by comicsads** [comment]
I feel like having a safer default is more important than having people opt to configure the settings on their own for less security. Most people likely aren't going to change the defaults and you're loosening the sandboxing for them for something they probably wont care about. If people want to change the settings sure but you're essentially forcing less security by default and expecting people to check github for every flatpak they have installed if they want to actually take advantage of the sandboxing or have an opinion about it (I didn't even know this github page existed before today)

**Comment by lionirdeadman** [comment]
I've decided this is no longer what I want to do. I'll wait for Discord to push for newer Electron with the file portal.

**Comment by guihkx** [comment]
> I've decided this is no longer what I want to do. I'll wait for Discord to push for newer Electron with the file portal.

Thank you for that. However, I honestly think this won't be happening anytime soon. :(

I'm not sure if this has been said before (nor if it's actually doable), but:

As an alternative, you could look into replacing Discord's Electron binary with your own, most recent version. Like this AUR package does:

https://aur.archlinux.org/packages/discord_arch_electron/

Of course it might cause some other issues, so this change could be pushed to the beta branch first for people to test it.

**Comment by lionirdeadman** [comment]
> Thank you for that. However, I honestly think this won't be happening anytime soon. :(

It depends if Electron project decides to backport the changes which make it possible. They tagged it as minor so I believe it might be possible.

> As an alternative, you could look into replacing Discord's Electron binary with your own, most recent version. Like this AUR package does:

This will not happen unless I get Discord's approval because it requires modifying their binaries especially considering their TOS which prohibits client modifications.

**Comment by guihkx** [comment]
Ooof, there's that too...

> It depends if Electron project decides to backport the changes which make it possible. They tagged it as minor so I believe it might be possible.

Fingers crossed then 🤞

**Pull request closed without merging**
