### PR TITLE
Bump to 0.0.8

### LINKED ISSUE #45: They just released 0.0.8 (??)
I don't even know what the hell is going on at this point.

### PR DESCRIPTION
**Pull request by beheh**
Looks like it's a busy day over at Discord HQ.

Closes #45.

### CODE REVIEW

**Comment by beheh** [comment]
No, looks like this is some internal stuff:

```diff
diff -r discord-0.0.7/Discord/resources/build_info.json discord-0.0.8/Discord/resources/build_info.json
3c3
<   "version": "0.0.7"
---
>   "version": "0.0.8"
```

```diff
diff -r discord-0.0.7/Discord/resources/app.asar/app_bootstrap/request.js discord-0.0.8/Discord/resources/app.asar/app_bootstrap/request.js
10a11,14
> var _querystring = require('querystring');
> 
> var _querystring2 = _interopRequireDefault(_querystring);
> 
80c84,85
<       var nr = _electron.net.request(strictOpts);
---
>       var qs = _querystring2.default.stringify(strictOpts.qs);
>       var nr = _electron.net.request(_extends({}, strictOpts, { url: strictOpts.url + '?' + qs }));
```

**Comment by beheh** [comment]
It also seems like 3a5153076d185f2e949a68d5c8ff50247e9dbb0d works for me with the build from this PR.

**Comment by simoniz0r** [comment]
I'm not sure you should be posting that... I'm fairly sure it's against Discord's Terms of Service to view the contents of that asar.

**Comment by phase** [comment]
We need to wait for @TingPing or another maintainer to merge it.

**Comment by simoniz0r** [comment]
I'm aware, but he commented without merging it lol... You should always make the target binary of a universal package executable in your build process...  I don't see why you'd be waiting for that or even to see what this fixes as people cannot use the out of date version at all unless they do not restart their client.

**Comment by barthalion** [comment]
> I'm aware, but they commented without merging it lol... You should always make the target binary of a universal package executable in your build process...

This is exactly what happened if you look at comments above: https://github.com/flathub/com.discordapp.Discord/pull/46#issuecomment-454615819

**Comment by simoniz0r** [comment]
Yes, I'm aware of that too.  What makes zero sense is that it took 8 hours to merge this.  Users had to wait 8 hours for ***literally no reason***.  @TingPing there's really no reason to hold up PRs being merged like that.

**Comment by kirbyfan64** [comment]
Or he could've been, you know *sleeping* or something?

**Comment by barthalion** [comment]
I'm sorry we are not robots, @simoniz0r.

**Comment by simoniz0r** [comment]
I'm not implying that you are robots.  @TingPing replied asking if something was fixed ***AFTER*** this PR was submitted.  Please don't attack me if you're not going to read into what I'm saying...

**Comment by TingPing** [comment]
While I probably should have just merged it I guess the immediate thought going through my mind was *Well I instantly merged the last PR and the package was entirely broken*. Now you can argue the update popup makes it unusable anyway but that is better than failing to start entirely with no feedback at all.

**Comment by simoniz0r** [comment]
Maybe you should actually like use it yourself if you're going to be maintaining it?

**Comment by TingPing** [comment]
I use the software I just don't close it often nor do I use it in my sleep. I'm so very sorry for an 8 hour inconvenience in your life and for Discord not being able to sanely release software.

**Comment by kirbyfan64** [comment]
@simoniz0r You don't even use Flatpaks, why are you bringing it up?

**Comment by simoniz0r** [comment]
@kirbyfan64 because I don't like to see people complain about not being able to use Discord for no good reason.

**Comment by simoniz0r** [comment]
> I use the software I just don't close it often nor do I use it in my sleep. I'm so very sorry for an 8 hour inconvenience in your life and for Discord not being able to sanely release software.

It would have taken you a whole 5 seconds to hit the merge button when you commented...
There's literally no reason to hold up Discord builds ever.  If there's a bug, you can't fix it.  That would be against the ToS in most cases.  You pretty much just have to ship it as is and hope that it works.  As long as you're doing everything correctly on your end, there's nothing more you can do other than hope they didn't muck things up.

**Comment by mikroskeem** [comment]
>because I don't like to see people complain about not being able to use Discord for no good reason

@simoniz0r do you see anyone else here complaining? Why are you attacking people for a problem (specifically: people coming here **complaining**) that does not exist? Really - piss off, maintain your own Discord flatpaks and that's it, it doesn't take much to "be a better maintainer". Instead you're complaining here and wasting everyone's time. What do you achieve with that?

That's right, nothing but hatred :tada: 

Just my 2c. Thanks for reading, have a good (or bad?) day.

**Comment by kirbyfan64** [comment]
Hey, can someone please lock this? It's really not going to get any better at this point.

**Pull request merged**
