### PR TITLE
Fix wayland detection in some systems

### PR DESCRIPTION
**Pull request by pedrovanzella**
Flatpak seems to be setting ${WAYLAND_DISPLAY} to an absolute path in some systems. This was causing the wayland check to fail because we were looking for the wrong path. This change should support all cases now.

Same fix applied to https://github.com/flathub/com.slack.Slack/pull/271

### CODE REVIEW

**Comment by mvdan** [comment]
Echoing my reply from https://github.com/flathub/com.slack.Slack/pull/271#issuecomment-1992725897 - this fixes Wayland for me as well :)

**Comment by pedrovanzella** [comment]
Slack PR has been merged and it's been working great. Can we merge this PR too?

**Comment by pedrovanzella** [comment]
Patch works with the latest update

**Comment by pedrovanzella** [comment]
Looks like this patch is no longer needed.

**Comment by mvdan** [comment]
@pedrovanzella how did you arrive at that conclusion? It seems very much still needed for me on Arch Linux running Sway.

**Comment by pedrovanzella** [comment]
Reopening. I tested Discord without this patch on my system, running Plasma 6.0.3 on Arch, Wayland and nvidia, and `xlsclients` didn't report anything.

I assumed, since there was no chatter in this PR, this was just some configuration weirdness on my system.

**Comment by mvdan** [comment]
Well, I'm not sure if I have any similar weirdness on my end, but I don't recall touching anything related to wayland or flatpak in the last few months, and I still reproduce the issue :) Seeing as how the fix is fairly easy, and the Slack app merged it, I'd lean towards merging this one too, unless anyone can reason that it's wrong.

**Comment by lionirdeadman** [comment]
bot, build

**Comment by pedrovanzella** [comment]
Working fine with the latest update. KDE 6.0.4, Arch, Nvidia.

**Comment by salilmishra23** [comment]
Discord starts with X11 even after setting the wayland socket override on Fedora 40, KDE Plasma 6.

```
❯ cat ~/.local/share/flatpak/overrides/com.discordapp.Discord
[Context]
sockets=wayland;
devices=dri;
```

Would be great if this gets merged!

**Comment by mvdan** [comment]
Friendly nudge @lionirdeadman :) Can we help in any way? I don't personally use GNOME to test it on there, but perhaps we can find someone else who does.

**Comment by pedrovanzella** [comment]
Given that this relates to Electron, and Slack has had this same changeset applied to for a couple of months now with no reports of side effects, I'm pretty confident in this PR.

But yeah, if there is any way I can help get this merged, please let me know!

**Comment by lionirdeadman** [comment]
Sorry again for the wait - just tried and looks good to me. Merging.

**Pull request merged**
